#!/bin/bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pidfile=${DIR}/tillweb.pid

cd "${DIR}"

export DJANGO_SETTINGS_MODULE=tillweb_infra.settings_production
export LANG=en_GB.UTF8
export LC_CTYPE=en_GB.UTF8
test -f ${pidfile} && /sbin/start-stop-daemon --stop --signal=INT --pidfile=${pidfile} --retry 10 --oknodo
mkdir -p "${DIR}/static"
python3 manage.py collectstatic --noinput
exec uwsgi \
     --plugins python35 \
     --socket 127.0.0.1:3861 \
     --wsgi-file tillweb_infra/wsgi.py \
     --lazy-apps \
     --processes 8 \
     --threads 4 \
     --master \
     --pidfile ${pidfile} \
     --post-buffering 1 \
     --daemonize ${DIR}/uwsgi.log
