#!/bin/bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "${DIR}"

export DJANGO_SETTINGS_MODULE=tillweb_infra.settings
export LANG=en_GB.UTF8
export LC_CTYPE=en_GB.UTF8
exec python3 -Wd manage.py runserver
