#!/bin/bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pidfile=${DIR}/tillweb.pid

cd "${DIR}"

test -f ${pidfile} && /sbin/start-stop-daemon --stop --signal=INT --pidfile=${pidfile} --retry 10 --oknodo || echo "No daemon was running"
rm -f ${pidfile}
